### ISSUE TITLE
python file for inference

### ISSUE THREAD

**Issue by AnakTeka** [zihaomu/deep-text-recognition-benchmark#1]
I can't seem find the python file that you mentioned `text_recog.py`, where am I supposed to get that file?

**Comment by zihaomu** [comment]
@AnakTeka Sorry for late reply. The text_rcog.py is https://github.com/zihaomu/opencv/blob/GSoC_digit_text_detect_and_recog/samples/dnn/text_detection.py. And the C++ version is https://github.com/zihaomu/opencv/blob/GSoC_digit_text_detect_and_recog/samples/dnn/text_detection.cpp. 
Hope it is helpful.
